# Generated by Django 2.2.1 on 2019-06-03 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190602_0622'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='micro_blog',
            new_name='blog',
        ),
    ]
