# Generated by Django 2.2.2 on 2019-07-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
