# Generated by Django 2.2.2 on 2019-07-28 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('send', '0002_mail_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mail',
            old_name='file',
            new_name='sent_file',
        ),
    ]
